language: node_js

node_js:
  - stable

services: 
  - mongodb

install:
  - npm install

# Wait for mongodb
before_script:
  - sleep 15
  
script:
  - npm test
  
# Send coverage data to Coveralls
after_script:
  - cat coverage/lcov.info | node_modules/coveralls/bin/coveralls.js  

notifications:
  email:
    recipients:
      - andreas.leinen@imicros.de
    on_success: never # default: change
    on_failure: always # default: always